POST http://localhost:3333/adress
Content-Type: application/json

{
    "cep": "95860000",
    "estado":"RS",
    "cidade":"C4dade",
    "bairro":"Centro", 
    "numero":"1234567890", 
    "complemento":"complementado"
}

###

GET http://localhost:3333/adress

###

PUT http://localhost:3333/adress/4fce7278-e49c-413f-9396-44d03f7d42db
Content-Type: application/json

{
    "cep": "pudooasdoasdo",
    "estado":"RSss",
    "cidade":"Cidade",
    "bairro":"Centro", 
    "numero":"00", 
    "complemento":"complementado"
}

###

DELETE http://localhost:3333/adress/4fce7278-e49c-413f-9396-44d03f7d42db

###

POST http://localhost:3333/adress/test
Content-Type: application/json

{
    "cep": "95860000",
    "estado":"RS",
    "cidade":"Cidade",
    "bairro":"Centro", 
    "numero":"1234567890", 
    "complemento":"complementado"
}